name: happy-ml
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - scikit-learn
  - matplotlib
  - pyarrow
  - seaborn
  - tqdm
  - imbalanced-learn
  - optuna
  - xgboost
  - pip
  - pip:
    - optuna
    - ipywidgets
    - tabulate
    - lazypredict-nightly
    - networkx
    - shap
    - lime
    - skops
    - streamlit
    - plotly